version: '3.8'
services:
  dev-db:
    image: postgres:15.4
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sports
    networks:
      - Bo4um
networks:
  Bo4um: